import { Match, LeaderboardUser } from "./types";

export const TRANSLATIONS = {
  en: {
    appName: "PlayZone Pro BD",
    appSubtitle: "Premium Mobile Esports Tournament Hub",
    switchLanguage: "বাংলা সংস্করণ",
    lobby: "Match Lobby",
    myMatches: "My Matches",
    wallet: "My Wallet",
    leaderboard: "Leaderboard",
    adminMode: "Admin Controls",
    balance: "Coin Balance",
    deposit: "Loaded Coins",
    winning: "Earned Coins",
    addMoney: "Add Coins",
    withdraw: "Redeem Coins",
    gameCategories: "Games",
    upcoming: "Upcoming",
    ongoing: "Ongoing",
    completed: "Completed",
    entryFee: "Entry Fee",
    prizePool: "Total Prize",
    perKill: "Per Kill",
    version: "Version",
    map: "Map",
    type: "Type",
    slotsLeft: "slots left",
    matchDetails: "Match Details",
    joinBtn: "Join Match",
    joinedBtn: "Joined Slot",
    fullBtn: "Slots Full",
    bookingTitle: "Book Your Slot Seat",
    gameUidLabel: "Game UID / Character ID",
    gameIgnLabel: "In-Game Name (IGN)",
    submitBooking: "Confirm Slot Booking",
    sufficientBalanceErr: "Insufficient Coins! Please obtain/add coins to your wallet first.",
    roomCredentials: "Room ID & Password",
    noRoomCredentials: "Room ID & Password will be shared 15 minutes before the match starts.",
    submitScreenshot: "Upload Winner Proof",
    uploadProofSuccess: "Proof uploaded successfully! Admin will review shortly.",
    rulesTitle: "General Match Rules",
    rule1: "1. Hackers, emulators, or teaming up are strictly forbidden. Banned instantly.",
    rule2: "2. Must join the custom room using the exact Game IGN submitted.",
    rule3: "3. Screenshot of results must be uploaded for verification of wins.",
    trxHistory: "Transaction History",
    noTrx: "No transactions yet.",
    amtLabel: "Amount",
    statusLabel: "Status",
    dateLabel: "Date",
    trxIdLabel: "TrxID",
    paymentGateway: "Mobile Banking Gateways & Stores",
    enterTrxDetails: "Submit Transaction Details",
    selectProvider: "Select Mobile Provider",
    sendMoneyInstruct: "To obtain virtual eSports coins, send payment equivalent to our official virtual store number +8801700000000 and enter the Receipt Transaction ID (TrxID) below:",
    sendMoneyWithdraw: "Enter your account number and coin count to redeem. Standard verification takes up to 4 hours.",
    enterNumber: "Mobile Number",
    confirmDeposit: "Submit Coin Acquisition Request",
    confirmWithdraw: "Submit Redemptions Request",
    adminDashboard: "Admin Management Station",
    createMatch: "Publish Custom Live Match",
    createMatchBtn: "Publish Match",
    walletApprovals: "Approve Wallet Deposits",
    noPendingDeposits: "No pending deposit requests.",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    submitMatchResults: "Submit Living Results & Distribute Coins",
    selectMatchToFinalize: "Select Completed Match to Publish Results",
    winnerIgn: "Winner In-Game Name",
    playerKillsList: "Submit Match Standings (Player Name & Kills)",
    distributePrizes: "Declare Results & Pay Out Players",
    resultsDeclared: "Results verified & distributed successfully!"
  },
  bn: {
    appName: "প্লেজোন প্রো বিডি",
    appSubtitle: "প্রিমিয়াম মোবাইল টুর্নামেন্ট এপস",
    switchLanguage: "English Version",
    lobby: "ম্যাচ লবি",
    myMatches: "আমার ম্যাচ",
    wallet: "আমার ওয়ালেট",
    leaderboard: "সেরা খেলোয়াড়",
    adminMode: "এডমিন ড্যাশবোর্ড",
    balance: "মোট কয়েন",
    deposit: "লোডকৃত কয়েন",
    winning: "অর্জিত কয়েন",
    addMoney: "কয়েন লোড করুন",
    withdraw: "কয়েন রিডিম করুন",
    gameCategories: "গেমস সমূহ",
    upcoming: "আসন্ন ম্যাচ",
    ongoing: "চলমান ম্যাচ",
    completed: "সমাপ্ত ম্যাচ",
    entryFee: "এন্ট্রি ফি",
    prizePool: "মোট প্রাইজ",
    perKill: "প্রতি কিল প্রাইজ",
    version: "ভার্সন",
    map: "ম্যাপ",
    type: "টাইপ",
    slotsLeft: "টি সীট ফাকা",
    matchDetails: "ম্যাচ বিবরণী",
    joinBtn: "জয়েন করুন",
    joinedBtn: "জয়েন করেছেন",
    fullBtn: "স্লট ফুল",
    bookingTitle: "আপনার সীট স্লট বুক করুন",
    gameUidLabel: "গেম ইউআইডি (UID)",
    gameIgnLabel: "গেম নেম (IGN)",
    submitBooking: "স্লটি বুকিং নিশ্চিত করুন",
    sufficientBalanceErr: "❌ পর্যাপ্ত কয়েন নেই! দয়া করে ওয়ালেটে কয়েন এড করুন।",
    roomCredentials: "রুম আইডি ও পাসওয়ার্ড",
    noRoomCredentials: "খেলার রুম আইডি ও পাসওয়ার্ড ম্যাচ শুরু হওয়ার ১৫ মিনিট আগে দেওয়া হবে।",
    submitScreenshot: "স্ক্রিনশট আপলোড দিন",
    uploadProofSuccess: "প্রমাণ আপলোড হয়েছে! এডমিন শীঘ্রই যাচাই করবে।",
    rulesTitle: "গুরুত্বপূর্ণ ম্যাচ নিয়মাবলী",
    rule1: "১. কোনো প্রকার হ্যাক, ইমুলেটর বা টিমিং করা সম্পূর্ণ নিষেধ। করলে আইডি ব্যান করা হবে।",
    rule2: "২. রেজিষ্ট্রেশন করার সময় সঠিক গেম ইন-গেম নেম (IGN) ব্যবহার করতে হবে।",
    rule3: "৩. জয়ের পর কেল ও বিজয়ের প্রমাণ হিসেবে অবশ্যই স্ক্রিনশট দিতে হবে।",
    trxHistory: "লেনদেন এর ইতিহাস",
    noTrx: "কোনো লেনদেন রেকর্ড নেই।",
    amtLabel: "পরিমাণ",
    statusLabel: "অবস্থা",
    dateLabel: "তারিখ",
    trxIdLabel: "লেনদেন আইডি (TrxID)",
    paymentGateway: "মোবাইল ব্যাংকিং কয়েন স্টোর",
    enterTrxDetails: "কয়েন পেমেন্ট বিস্তারিত",
    selectProvider: "মোবাইল অপারেটর সিলেক্ট করুন",
    sendMoneyInstruct: "বিকাশ/নগদ/রকেট অ্যাপের মাধ্যমে নিচে দেওয়া নাম্বারে সেন্ট মানি করুন। ভার্চুয়াল স্টোর নাম্বার: +৮৮০১৭০০০০০০০০। অতপর প্রেরিত পেমেন্ট তথ্যের ট্রানজেকশন আইডি (TrxID) নিচে লিখুন:",
    sendMoneyWithdraw: "ভার্চুয়াল কয়েন রিডিম করার জন্য আপনার পার্সোনাল মোবাইল নাম্বার এবং কয়েন এর পরিমাণ লিখুন। ৪ ঘন্টার মধ্যে প্রসেস সম্পন্ন হবে।",
    enterNumber: "মোবাইল নাম্বার",
    confirmDeposit: "কয়েন লোড রিকোয়েস্ট পাঠান",
    confirmWithdraw: "কয়েন রিডিম করানোর আবেদন",
    adminDashboard: "এডমিন কন্ট্রোল সেন্টার",
    createMatch: "নতুন কাস্টম ম্যাচ প্রকাশ করুন",
    createMatchBtn: "ম্যাচ পাবলিশ করুন",
    walletApprovals: "কয়েন্ট লোড রিকোয়েস্ট অ্যাপ্রুভাল",
    noPendingDeposits: "কোনো ডিপোজিট পেন্ডিং নেই।",
    approveBtn: "অনুমোদন করুন",
    rejectBtn: "বাতিল করুন",
    submitMatchResults: "খেলার ফলাফল প্রকাশ ও কয়েন বিতরণ",
    selectMatchToFinalize: "সমাপ্ত ম্যাচ সিলেক্ট করুন",
    winnerIgn: "বিজয়ীর গেম নেম (IGN)",
    playerKillsList: "খেলোয়াড়দের স্কোর এবং কিল লিস্ট সাবমিট করুন",
    distributePrizes: "ফলাফল ঘোষণা ও কয়েন বিতরণ করুন",
    resultsDeclared: "বিজয়ী খেলোয়াড়দের একাউন্টে জয়ের কয়েন যুক্ত হয়েছে!"
  }
};

export const SEED_MATCHES: Match[] = [
  {
    id: "match-ff-1",
    game: "Free Fire",
    matchNum: 101,
    dateTime: "Today, 08:30 PM",
    title: "Ramadan Bermuda Special Solo",
    prizePool: 650,
    entryFee: 20,
    perKill: 5,
    version: "Mobile",
    map: "Bermuda Esports",
    type: "Solo",
    totalSlots: 48,
    status: "Upcoming",
    slots: Array.from({ length: 48 }, (_, i) => ({
      slotNo: i + 1,
      gameId: "match-ff-1",
      gameName: "Free Fire",
      isBooked: i < 30, // 30 joined initially
      registeredBy: i < 30 ? `Player_${i + 5}` : undefined
    }))
  },
  {
    id: "match-ff-2",
    game: "Free Fire",
    matchNum: 205,
    dateTime: "Today, 09:30 PM",
    title: "Clash Squad Clash Master 4v4",
    prizePool: 400,
    entryFee: 40,
    perKill: 0,
    version: "Mobile",
    map: "Kalahari",
    type: "Squad",
    totalSlots: 8,
    status: "Upcoming",
    slots: Array.from({ length: 8 }, (_, i) => ({
      slotNo: i + 1,
      gameId: "match-ff-2",
      gameName: "Free Fire",
      isBooked: i < 4,
      registeredBy: i < 4 ? `Squad_Team_${i + 1}` : undefined
    }))
  },
  {
    id: "match-pubg-1",
    game: "PUBG Mobile",
    matchNum: 301,
    dateTime: "Today, 10:00 PM",
    title: "Erangel Prime Duo Battle",
    prizePool: 1200,
    entryFee: 30,
    perKill: 10,
    version: "Mobile",
    map: "Erangel",
    type: "Duo",
    totalSlots: 50,
    status: "Ongoing",
    roomId: "7483920",
    roomPass: "9988",
    slots: Array.from({ length: 50 }, (_, i) => ({
      slotNo: i + 1,
      gameId: "match-pubg-1",
      gameName: "PUBG Mobile",
      isBooked: true,
      registeredBy: `PubgUser_${i + 1}`
    }))
  },
  {
    id: "match-ludo-1",
    game: "Ludo King",
    matchNum: 405,
    dateTime: "Today, 07:15 PM",
    title: "Ludo King Fast Track 4-Way",
    prizePool: 300,
    entryFee: 15,
    perKill: 0,
    version: "Mobile",
    map: "Classic Board",
    type: "Solo",
    totalSlots: 4,
    status: "Upcoming",
    slots: [
      { slotNo: 1, gameId: "match-ludo-1", gameName: "Ludo King", isBooked: true, registeredBy: "LudoPro_1S" },
      { slotNo: 2, gameId: "match-ludo-1", gameName: "Ludo King", isBooked: true, registeredBy: "Gamer_Naim" },
      { slotNo: 3, gameId: "match-ludo-1", gameName: "Ludo King", isBooked: false },
      { slotNo: 4, gameId: "match-ludo-1", gameName: "Ludo King", isBooked: false }
    ]
  },
  {
    id: "match-mlbb-1",
    game: "Mobile Legends",
    matchNum: 502,
    dateTime: "Tomorrow, 08:00 PM",
    title: "MLBB Land of Dawn Grand Arena",
    prizePool: 800,
    entryFee: 25,
    perKill: 5,
    version: "Mobile",
    map: "Land of Dawn",
    type: "Squad",
    totalSlots: 10,
    status: "Upcoming",
    slots: Array.from({ length: 10 }, (_, i) => ({
      slotNo: i + 1,
      gameId: "match-mlbb-1",
      gameName: "Mobile Legends",
      isBooked: i < 6,
      registeredBy: i < 6 ? `ML_Team_${i + 1}` : undefined
    }))
  },
  {
    id: "match-dls-1",
    game: "DLS",
    matchNum: 601,
    dateTime: "Tomorrow, 09:00 PM",
    title: "Dream League Soccer Pro Cup 1v1",
    prizePool: 500,
    entryFee: 15,
    perKill: 0,
    version: "Mobile",
    map: "Stadium Arena",
    type: "Solo",
    totalSlots: 8,
    status: "Upcoming",
    slots: Array.from({ length: 8 }, (_, i) => ({
      slotNo: i + 1,
      gameId: "match-dls-1",
      gameName: "DLS",
      isBooked: i < 3,
      registeredBy: i < 3 ? `Striker_${i + 1}` : undefined
    }))
  },
  {
    id: "match-ff-con-1",
    game: "Free Fire",
    matchNum: 99,
    dateTime: "Yesterday, 06:00 PM",
    title: "Bermuda Rush Duel",
    prizePool: 500,
    entryFee: 15,
    perKill: 4,
    version: "Mobile",
    map: "Bermuda",
    type: "Solo",
    totalSlots: 48,
    status: "Completed",
    slots: [],
    results: [
      { rank: 1, playerIgn: "Boss_Rifat", kills: 9, prizeWon: 150 },
      { rank: 2, playerIgn: "SkyBD_Fire", kills: 6, prizeWon: 100 },
      { rank: 3, playerIgn: "Abir_Esport", kills: 4, prizeWon: 60 },
      { rank: 4, playerIgn: "OP_Noyon", kills: 2, prizeWon: 30 }
    ]
  },
  {
    id: "match-ludo-con-1",
    game: "Ludo King",
    matchNum: 88,
    dateTime: "Yesterday, 05:00 PM",
    title: "Ludo King Mini Cup #20",
    prizePool: 200,
    entryFee: 10,
    perKill: 0,
    version: "Mobile",
    map: "Classic Master",
    type: "Solo",
    totalSlots: 4,
    status: "Completed",
    slots: [],
    results: [
      { rank: 1, playerIgn: "Rashed_BD", kills: 0, prizeWon: 150 },
      { rank: 2, playerIgn: "Apon_YT", kills: 0, prizeWon: 50 },
      { rank: 3, playerIgn: "Mithu_N", kills: 0, prizeWon: 0 }
    ]
  }
];

export const SEED_LEADERBOARD: LeaderboardUser[] = [
  { rank: 1, gamertag: "Boss_Rifat", totalWon: 7420, matchesPlayed: 84, totalKills: 512 },
  { rank: 2, gamertag: "SkyBD_Fire", totalWon: 5190, matchesPlayed: 62, totalKills: 382 },
  { rank: 3, gamertag: "Gamer_Naim", totalWon: 4560, matchesPlayed: 50, totalKills: 140 },
  { rank: 4, gamertag: "Rashed_BD", totalWon: 3900, matchesPlayed: 45, totalKills: 0 },
  { rank: 5, gamertag: "Abir_Esport", totalWon: 3450, matchesPlayed: 56, totalKills: 290 },
  { rank: 6, gamertag: "Apon_YT", totalWon: 2900, matchesPlayed: 32, totalKills: 110 }
];
